### ISSUE TITLE
LoadingButton disappear after setting customFontFamily attribute

### ISSUE THREAD

**Issue by nazebzurati** [droidbond/LoadingButton#3]
### Description

LoadingButton disappear when setting custom font family but it works after compile and run on Android device.

### Environment:

- Operating System: Pop!_OS 19.04 x86_64
- Android Studio 3.5
- Build #AI-191.8026.42.35.5791312, built on August 9, 2019
- JRE: 1.8.0_202-release-1483-b49-5587405 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Linux 5.0.0-29-generic

### Step to reproduce

1. Download font (my case: roboto) using built-in feature as [explained here](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts#via-android-studio)
2. Add LoadingButton into a layout (my case: VerticalLinearLayout)
3. Add customFontFamily attrib
   ```
   app:customFontFamily="@font/roboto"
   ```
4. The LoadingButton will dissappear from layout but still exist in component tree. You will get issue message titled 'Failed to instantiate one or more classes'
5. Build and run into Android device
6. LoadingButton exist with the Roboto font

### Log

Exception details as provided below:
```
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090000 could not be retrieved.
	at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:342)
	at android.support.v4.content.res.ResourcesCompat.getFont(ResourcesCompat.java:207)
	at com.droidbond.loadingbutton.LoadingButton.updatedText(LoadingButton.kt:188)
	at com.droidbond.loadingbutton.LoadingButton.initView(LoadingButton.kt:128)
	at com.droidbond.loadingbutton.LoadingButton.<init>(LoadingButton.kt:52)
	at com.droidbond.loadingbutton.LoadingButton.<init>(LoadingButton.kt:35)
	at com.droidbond.loadingbutton.LoadingButton.<init>(LoadingButton.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:323)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:394)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:200)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:572)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:698)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by didarul-codes** [comment]
IDE editor couldn't find the font while in preview as it was in another module. If you need to visualize the button in editor, do not set `app:customFontFamily` in xml.
Use the latest release and set custom font typeface pragamatically as `custombtn.setTypeFace(typeface)
`
